### PR TITLE
atf: Add support for CR7

### PR DESCRIPTION
**Pull request by rshym**

### CODE REVIEW

**Comment by rshym** [comment]
This patch was successfully tested in cockpit-rcar for KF.
As result, I observed messages in console from CR7 (no messages without this patch), and product successfully starts.
Two patches were taken as-is from the proprietary repo.

**Comment by lorc** [comment]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
"Acked-by "is added.
All patch files are rebased on current sources.
The work of Valerii Chubar on rebasing is mentioned in the commit message.
Successfully tested on KF.
After applying of the patch we see in console:
```
NOTICE:  BL31: Built : 12:33:33, Apr  6 2021
ROS CIO Server START  Dec  ROS CIO Server START  Dec  2 2021 09:16:41
CIO loc_CioMainLoop START
CIO Dummy locInit
CIO R-CAR_cio_canfd driver channel 0 init, IRQ 62 OK
CIO R-CAR_cio_canfd driver channel 1 init, IRQ 62 OK
CIO R-Car_WM driver device 0 init ...  OK
CIO R-Car_WM driver device 1 init ...  OK
CIO R-Car_WM driver device 2 init ...  OK
CIO R-Car_WM driver device 3 init ...  OK

Taurus Virtual Peripheral Server Dec  2 2021 09:16:41 START
ROS CIO Server END
CR7 START
about WM init
CIO Channel 1 START
/CIO_MSG1
/CIO_RET1
CIO WM device 1 open ...  OK


U-Boot 2020.10 (Oct 05 2020 - 15:15:32 +0000)
```

**Comment by rshym** [comment]
@iusyk could you please merge?

**Pull request merged**
