### PR TITLE
doma: override doma u-boot branch from common project

### PR DESCRIPTION
**Pull request by arminn**
Cockpit demo will have specific pathces on u-boot.

Signed-off-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>

### CODE REVIEW

**Comment by rshym** [comment]
No comments on the functional part, only regarding the commit message.

I would propose to reword the commit message due to following reasons:
- misprint in 'patches';
- usage of 'cockpit demo' is misleading because we have a separate product with that name;
- header line looks not very clear (what is 'common project'?).
Maybe it's better to use something like 'customize URL' ...

Also, it's good to mention in the comment that this PR needs to be merged after https://github.com/xen-troops/meta-xt-common/pull/24

**Comment by rshym** [comment]
With reworded commit message:
`Acked-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>`

**Comment by arminn** [comment]
@rshym description updated - plz look on it

**Comment by rshym** [comment]
LGTM. Ack is already provided.

**Comment by arminn** [comment]
ack added

**Pull request merged**
